services:
  - type: web
    name: job-scraper-platform
    runtime: node
    startCommand: npm run build && cd server && npm start
    buildCommand: npm install && cd client && npm install
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGO_URI
        scope: build
      - key: JWT_SECRET
        scope: build
      - key: OPENAI_API_KEY
        scope: build
